### ISSUE TITLE
Make it possible to assign a name to a nic inside a container

### ISSUE THREAD

**Issue by grimpy** [g8os/core0#256]
```yaml
 - type: vlan
    id: "0"
    name: "public"
    config:
      dhcp: false
      cidr: 192.168.58.22/24
      gateway: 192.168.58.254
      dns: [8.8.8.8]
```

I propose to add a name field to the nic struct
