### ISSUE TITLE
Add support for automatic connection to zerotier network during core0 boot

### ISSUE THREAD

**Issue by zaibon** [g8os/core0#32]

**Comment by muhamadazmy** [comment]
add this to core0 config (can be a new toml file under /config)
```toml
## Joining a network
[startup."join-network"]
name = "zerotier.join"
after = ["zerotier"]

[startup."join-network".args]
network = "565799d8f603a32c"
```
